//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.1。
// 

using System.Xml.Serialization;

namespace Com.Boc.Icms.DoNetSDK.Bean
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(ElementName = "batch", Namespace = "", IsNullable = false)]
    public partial class PostInfo
    {

        private business_info[] business_infoField;

        /// <remarks/>
        [XmlElement("business_info")]
        public business_info[] business_info
        {
            get
            {
                return this.business_infoField;
            }
            set
            {
                this.business_infoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class business_info
    {

        private string biz_metadata1Field;

        private string biz_metadata2Field;

        private string biz_metadata3Field;

        private string source_systemField;

        private string create_provinceField;

        private string check_telnoField;

        private string achr_secField;

        private string cust_noField;

        private doc_info[] docs_infoField;

        private business_infoModi_meta modi_metaField;

        private string modi_timeField;

        /// <remarks/>
        public string biz_metadata1
        {
            get
            {
                return this.biz_metadata1Field;
            }
            set
            {
                this.biz_metadata1Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string biz_metadata2
        {
            get
            {
                return this.biz_metadata2Field;
            }
            set
            {
                this.biz_metadata2Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string biz_metadata3
        {
            get
            {
                return this.biz_metadata3Field;
            }
            set
            {
                this.biz_metadata3Field = value;
            }
        }

        /// <remarks/>
        public string source_system
        {
            get
            {
                return this.source_systemField;
            }
            set
            {
                this.source_systemField = value;
            }
        }

        /// <remarks/>
        public string create_province
        {
            get
            {
                return this.create_provinceField;
            }
            set
            {
                this.create_provinceField = value;
            }
        }

        /// <remarks/>
        public string check_telno
        {
            get
            {
                return this.check_telnoField;
            }
            set
            {
                this.check_telnoField = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string achr_sec
        {
            get
            {
                return this.achr_secField;
            }
            set
            {
                this.achr_secField = value;
            }
        }

        /// <remarks/>
        public string cust_no
        {
            get
            {
                return this.cust_noField;
            }
            set
            {
                this.cust_noField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("doc_info", IsNullable = false)]
        public doc_info[] docs_info
        {
            get
            {
                return this.docs_infoField;
            }
            set
            {
                this.docs_infoField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public business_infoModi_meta modi_meta
        {
            get
            {
                return this.modi_metaField;
            }
            set
            {
                this.modi_metaField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string modi_time
        {
            get
            {
                return this.modi_timeField;
            }
            set
            {
                this.modi_timeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class doc_info
    {

        private string pkuuidField;

        private string uniq_metadataField;

        private string index_metadata1Field;

        private string index_metadata2Field;

        private string index_metadata3Field;

        private string ext_metadataField;

        private pagedel[] delete_pageField;

        private page[] pagesField;

        private ver[] version_listField;

        private string data_typeField;

        private doc_infoOper_type oper_typeField;

        private doc_infoFull_index full_indexField;

        private doc_infoNew_version new_versionField;

        private doc_infoModi_meta modi_metaField;

        private string modi_timeField;

        private string securityField;

        private doc_infoArchieved archievedField;

        private string expire_dateField;

        /// <remarks/>
        public string pkuuid
        {
            get
            {
                return this.pkuuidField;
            }
            set
            {
                this.pkuuidField = value;
            }
        }

        /// <remarks/>
        public string uniq_metadata
        {
            get
            {
                return this.uniq_metadataField;
            }
            set
            {
                this.uniq_metadataField = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string index_metadata1
        {
            get
            {
                return this.index_metadata1Field;
            }
            set
            {
                this.index_metadata1Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string index_metadata2
        {
            get
            {
                return this.index_metadata2Field;
            }
            set
            {
                this.index_metadata2Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(IsNullable = true)]
        public string index_metadata3
        {
            get
            {
                return this.index_metadata3Field;
            }
            set
            {
                this.index_metadata3Field = value;
            }
        }

        /// <remarks/>
        public string ext_metadata
        {
            get
            {
                return this.ext_metadataField;
            }
            set
            {
                this.ext_metadataField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("pagedel", IsNullable = false)]
        public pagedel[] delete_page
        {
            get
            {
                return this.delete_pageField;
            }
            set
            {
                this.delete_pageField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("page", IsNullable = false)]
        public page[] pages
        {
            get
            {
                return this.pagesField;
            }
            set
            {
                this.pagesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("ver", IsNullable = false)]
        public ver[] version_list
        {
            get
            {
                return this.version_listField;
            }
            set
            {
                this.version_listField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string data_type
        {
            get
            {
                return this.data_typeField;
            }
            set
            {
                this.data_typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public doc_infoOper_type oper_type
        {
            get
            {
                return this.oper_typeField;
            }
            set
            {
                this.oper_typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public doc_infoFull_index full_index
        {
            get
            {
                return this.full_indexField;
            }
            set
            {
                this.full_indexField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public doc_infoNew_version new_version
        {
            get
            {
                return this.new_versionField;
            }
            set
            {
                this.new_versionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public doc_infoModi_meta modi_meta
        {
            get
            {
                return this.modi_metaField;
            }
            set
            {
                this.modi_metaField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string modi_time
        {
            get
            {
                return this.modi_timeField;
            }
            set
            {
                this.modi_timeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string security
        {
            get
            {
                return this.securityField;
            }
            set
            {
                this.securityField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public doc_infoArchieved archieved
        {
            get
            {
                return this.archievedField;
            }
            set
            {
                this.archievedField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string expire_date
        {
            get
            {
                return this.expire_dateField;
            }
            set
            {
                this.expire_dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class pagedel
    {

        private string page_indexField;

        /// <remarks/>
        [XmlAttribute(DataType = "integer")]
        public string page_index
        {
            get
            {
                return this.page_indexField;
            }
            set
            {
                this.page_indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class page
    {

        private postil postilField;

        private string page_indexField;

        private string doc_indexField;

        private string file_nameField;

        private pagePage_flag page_flagField;

        private pageOper_type oper_typeField;

        private string old_doc_indexField;

        private pageOld_page_flag old_page_flagField;

        private bool old_page_flagFieldSpecified;

        private pageModi_range modi_rangeField;

        private string modi_timeField;

        /// <remarks/>
        public postil postil
        {
            get
            {
                return this.postilField;
            }
            set
            {
                this.postilField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "integer")]
        public string page_index
        {
            get
            {
                return this.page_indexField;
            }
            set
            {
                this.page_indexField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "integer")]
        public string doc_index
        {
            get
            {
                return this.doc_indexField;
            }
            set
            {
                this.doc_indexField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string file_name
        {
            get
            {
                return this.file_nameField;
            }
            set
            {
                this.file_nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public pagePage_flag page_flag
        {
            get
            {
                return this.page_flagField;
            }
            set
            {
                this.page_flagField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public pageOper_type oper_type
        {
            get
            {
                return this.oper_typeField;
            }
            set
            {
                this.oper_typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "integer")]
        public string old_doc_index
        {
            get
            {
                return this.old_doc_indexField;
            }
            set
            {
                this.old_doc_indexField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public pageOld_page_flag old_page_flag
        {
            get
            {
                return this.old_page_flagField;
            }
            set
            {
                this.old_page_flagField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool old_page_flagSpecified
        {
            get
            {
                return this.old_page_flagFieldSpecified;
            }
            set
            {
                this.old_page_flagFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public pageModi_range modi_range
        {
            get
            {
                return this.modi_rangeField;
            }
            set
            {
                this.modi_rangeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string modi_time
        {
            get
            {
                return this.modi_timeField;
            }
            set
            {
                this.modi_timeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class postil
    {

        private string file_nameField;

        private string remarkField;

        private postilOper_type oper_typeField;

        private string modi_timeField;

        /// <remarks/>
        [XmlAttribute()]
        public string file_name
        {
            get
            {
                return this.file_nameField;
            }
            set
            {
                this.file_nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public postilOper_type oper_type
        {
            get
            {
                return this.oper_typeField;
            }
            set
            {
                this.oper_typeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string modi_time
        {
            get
            {
                return this.modi_timeField;
            }
            set
            {
                this.modi_timeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum postilOper_type
    {

        /// <remarks/>
        A,

        /// <remarks/>
        E,

        /// <remarks/>
        I,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum pagePage_flag
    {

        /// <remarks/>
        F,

        /// <remarks/>
        B,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum pageOper_type
    {

        /// <remarks/>
        A,

        /// <remarks/>
        E,

        /// <remarks/>
        I,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum pageOld_page_flag
    {

        /// <remarks/>
        F,

        /// <remarks/>
        B,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum pageModi_range
    {

        /// <remarks/>
        M,

        /// <remarks/>
        C,

        /// <remarks/>
        A,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class ver
    {

        private decimal ver_noField;

        private string modi_timeField;

        private string modi_byField;

        /// <remarks/>
        [XmlAttribute()]
        public decimal ver_no
        {
            get
            {
                return this.ver_noField;
            }
            set
            {
                this.ver_noField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string modi_time
        {
            get
            {
                return this.modi_timeField;
            }
            set
            {
                this.modi_timeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string modi_by
        {
            get
            {
                return this.modi_byField;
            }
            set
            {
                this.modi_byField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum doc_infoOper_type
    {

        /// <remarks/>
        A,

        /// <remarks/>
        E,

        /// <remarks/>
        D,

        /// <remarks/>
        I,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum doc_infoFull_index
    {

        /// <remarks/>
        [XmlEnum("")]
        Item,

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum doc_infoNew_version
    {

        /// <remarks/>
        [XmlEnum("")]
        Item,

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum doc_infoModi_meta
    {

        /// <remarks/>
        [XmlEnum("")]
        Item,

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum doc_infoArchieved
    {

        /// <remarks/>
        [XmlEnum("")]
        Item,

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true)]
    public enum business_infoModi_meta
    {

        /// <remarks/>
        [XmlEnum("")]
        Item,

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class delete_page
    {

        private pagedel[] pagedelField;

        /// <remarks/>
        [XmlElement("pagedel")]
        public pagedel[] pagedel
        {
            get
            {
                return this.pagedelField;
            }
            set
            {
                this.pagedelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class docs_info
    {

        private doc_info[] doc_infoField;

        /// <remarks/>
        [XmlElement("doc_info")]
        public doc_info[] doc_info
        {
            get
            {
                return this.doc_infoField;
            }
            set
            {
                this.doc_infoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class pages
    {

        private page[] pageField;

        /// <remarks/>
        [XmlElement("page")]
        public page[] page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class version_list
    {

        private ver[] verField;

        /// <remarks/>
        [XmlElement("ver")]
        public ver[] ver
        {
            get
            {
                return this.verField;
            }
            set
            {
                this.verField = value;
            }
        }
    }
}
