//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Boc.Icms.DoNetSDK.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Boc.Icms.DoNetSDK.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Number of connections is full! 的本地化字符串。
        /// </summary>
        internal static string s9801 {
            get {
                return ResourceManager.GetString("s9801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiving a command packet error, the head of ommand packet received is not CMMD! 的本地化字符串。
        /// </summary>
        internal static string s9802 {
            get {
                return ResourceManager.GetString("s9802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get absolute path error! 的本地化字符串。
        /// </summary>
        internal static string s9803 {
            get {
                return ResourceManager.GetString("s9803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name is the root directory. error! 的本地化字符串。
        /// </summary>
        internal static string s9804 {
            get {
                return ResourceManager.GetString("s9804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create file errors! 的本地化字符串。
        /// </summary>
        internal static string s9805 {
            get {
                return ResourceManager.GetString("s9805", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get header error! 的本地化字符串。
        /// </summary>
        internal static string s9806 {
            get {
                return ResourceManager.GetString("s9806", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive files timeout! 的本地化字符串。
        /// </summary>
        internal static string s9807 {
            get {
                return ResourceManager.GetString("s9807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompression error! 的本地化字符串。
        /// </summary>
        internal static string s9808 {
            get {
                return ResourceManager.GetString("s9808", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client block is too big! 的本地化字符串。
        /// </summary>
        internal static string s9809 {
            get {
                return ResourceManager.GetString("s9809", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return confirmation message error! 的本地化字符串。
        /// </summary>
        internal static string s9810 {
            get {
                return ResourceManager.GetString("s9810", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the folder error! 的本地化字符串。
        /// </summary>
        internal static string s9811 {
            get {
                return ResourceManager.GetString("s9811", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read folder error! 的本地化字符串。
        /// </summary>
        internal static string s9812 {
            get {
                return ResourceManager.GetString("s9812", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list is too long! 的本地化字符串。
        /// </summary>
        internal static string s9813 {
            get {
                return ResourceManager.GetString("s9813", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the file name error! 的本地化字符串。
        /// </summary>
        internal static string s9814 {
            get {
                return ResourceManager.GetString("s9814", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get file attributes error! 的本地化字符串。
        /// </summary>
        internal static string s9815 {
            get {
                return ResourceManager.GetString("s9815", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breakpoint continuingly access to the offset error! 的本地化字符串。
        /// </summary>
        internal static string s9816 {
            get {
                return ResourceManager.GetString("s9816", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Definition file read file position error! 的本地化字符串。
        /// </summary>
        internal static string s9817 {
            get {
                return ResourceManager.GetString("s9817", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The add side resume offset error! 的本地化字符串。
        /// </summary>
        internal static string s9818 {
            get {
                return ResourceManager.GetString("s9818", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform a delete exception! 的本地化字符串。
        /// </summary>
        internal static string s9819 {
            get {
                return ResourceManager.GetString("s9819", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Derived sub-process exception! 的本地化字符串。
        /// </summary>
        internal static string s9820 {
            get {
                return ResourceManager.GetString("s9820", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Third breakpoint continuingly is not finished, transfer timeout! 的本地化字符串。
        /// </summary>
        internal static string s9821 {
            get {
                return ResourceManager.GetString("s9821", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read data timeout! 的本地化字符串。
        /// </summary>
        internal static string s9825 {
            get {
                return ResourceManager.GetString("s9825", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read data exception! 的本地化字符串。
        /// </summary>
        internal static string s9826 {
            get {
                return ResourceManager.GetString("s9826", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write data timeout! 的本地化字符串。
        /// </summary>
        internal static string s9827 {
            get {
                return ResourceManager.GetString("s9827", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write data exception! 的本地化字符串。
        /// </summary>
        internal static string s9828 {
            get {
                return ResourceManager.GetString("s9828", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read data side Close! 的本地化字符串。
        /// </summary>
        internal static string s9829 {
            get {
                return ResourceManager.GetString("s9829", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write data side Close! 的本地化字符串。
        /// </summary>
        internal static string s9830 {
            get {
                return ResourceManager.GetString("s9830", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Establish a connection open failure! 的本地化字符串。
        /// </summary>
        internal static string s9831 {
            get {
                return ResourceManager.GetString("s9831", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read file timeout! 的本地化字符串。
        /// </summary>
        internal static string s9850 {
            get {
                return ResourceManager.GetString("s9850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 read the file exception! 的本地化字符串。
        /// </summary>
        internal static string s9851 {
            get {
                return ResourceManager.GetString("s9851", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write the file timeout! 的本地化字符串。
        /// </summary>
        internal static string s9852 {
            get {
                return ResourceManager.GetString("s9852", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write the file exception 的本地化字符串。
        /// </summary>
        internal static string s9853 {
            get {
                return ResourceManager.GetString("s9853", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to apply address! 的本地化字符串。
        /// </summary>
        internal static string s9875 {
            get {
                return ResourceManager.GetString("s9875", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply compression buffer failed! 的本地化字符串。
        /// </summary>
        internal static string s9876 {
            get {
                return ResourceManager.GetString("s9876", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open the local file name! 的本地化字符串。
        /// </summary>
        internal static string s9877 {
            get {
                return ResourceManager.GetString("s9877", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fstat obtain information failure! 的本地化字符串。
        /// </summary>
        internal static string s9878 {
            get {
                return ResourceManager.GetString("s9878", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send the head of ommand packet failure 的本地化字符串。
        /// </summary>
        internal static string s9879 {
            get {
                return ResourceManager.GetString("s9879", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read file error! 的本地化字符串。
        /// </summary>
        internal static string s9880 {
            get {
                return ResourceManager.GetString("s9880", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to send data header! 的本地化字符串。
        /// </summary>
        internal static string s9881 {
            get {
                return ResourceManager.GetString("s9881", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send data error! 的本地化字符串。
        /// </summary>
        internal static string s9882 {
            get {
                return ResourceManager.GetString("s9882", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive confirmation error! 的本地化字符串。
        /// </summary>
        internal static string s9883 {
            get {
                return ResourceManager.GetString("s9883", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to receive data header! 的本地化字符串。
        /// </summary>
        internal static string s9884 {
            get {
                return ResourceManager.GetString("s9884", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 logic_readSM failed to read data from the network! 的本地化字符串。
        /// </summary>
        internal static string s9885 {
            get {
                return ResourceManager.GetString("s9885", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompression error! 的本地化字符串。
        /// </summary>
        internal static string s9886 {
            get {
                return ResourceManager.GetString("s9886", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return to confirm the information (datahdr) error! 的本地化字符串。
        /// </summary>
        internal static string s9887 {
            get {
                return ResourceManager.GetString("s9887", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receives the command packet error! 的本地化字符串。
        /// </summary>
        internal static string s9888 {
            get {
                return ResourceManager.GetString("s9888", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTPrecv writing files error! 的本地化字符串。
        /// </summary>
        internal static string s9889 {
            get {
                return ResourceManager.GetString("s9889", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fseek failure! 的本地化字符串。
        /// </summary>
        internal static string s9890 {
            get {
                return ResourceManager.GetString("s9890", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The breakpoint continuingly offset error! 的本地化字符串。
        /// </summary>
        internal static string s9891 {
            get {
                return ResourceManager.GetString("s9891", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access to the side of address failure! 的本地化字符串。
        /// </summary>
        internal static string s9892 {
            get {
                return ResourceManager.GetString("s9892", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write to the side of address failure! 的本地化字符串。
        /// </summary>
        internal static string s9893 {
            get {
                return ResourceManager.GetString("s9893", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid socket 的本地化字符串。
        /// </summary>
        internal static string s9894 {
            get {
                return ResourceManager.GetString("s9894", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the host infomation error 的本地化字符串。
        /// </summary>
        internal static string s9895 {
            get {
                return ResourceManager.GetString("s9895", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing code error 的本地化字符串。
        /// </summary>
        internal static string s9896 {
            get {
                return ResourceManager.GetString("s9896", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select error 的本地化字符串。
        /// </summary>
        internal static string s9897 {
            get {
                return ResourceManager.GetString("s9897", resourceCulture);
            }
        }
    }
}
